### ISSUE TITLE
Test recently connectorized Talons

### ISSUE THREAD

**Issue by kajames** [FRC2706/blingServer#51]
A large number of new (and not-yet-used-on-robots) talons have been connectorixzed by the controls team. Each one of these should be:

- tested on plyboy
- given a CAN bus ID equal to their "serial number" (as labelled by Monique on each device)

**Comment by kevlam2706** [comment]
Is this the plan for CAN IDs going forward or will you be adhering to
the template from previous years (1, 2, 3, 4 for drivetrain etc)?

**Comment by kajames** [comment]
Plan is to reconfigure IDs to whatever software wants once the talons are
installed on a robot. Unique IDS just means there will be no collisions
when trying to do the reassignments
